server:
  port: 81
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/redis_cache?useSSL=false
    username: root
    password: qq20225415
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 100
logging:
  file:
    name: logs/xxx.log
  level:
    org.springframework.boot: error
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包