---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyongguang.
--- DateTime: 2022/10/27 21:06
---
---//优惠卷id
local voucherId =ARGV[1]
-- 用户id
local userId = ARGV[2]
--数据key
--库存key
local stockKey = 'seckill:stock'..voucherId
--订单key
local orderKey = 'seckill:order'..voucherId

--脚本业务
if(tonumber(redis.call('get',stockKey)<=0))then
    --库存不足
    return 1
end
--判断用户是否下单sismember orderKey userId
if(redis.call('sismember',orderKey,userId)==1)then
return 2
end
--扣库存incrby stockKey -1
redis.call('incrby',stockKey,-1)
--下单sadd(保存用户)
redis.call('sadd',orderKey,userId)
return 0