server:
  port: 9001
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          bindings:
            mq_consume:
              consumer:
                enabled: true
                broadcasting: false
          name-server: 127.0.0.1:9876
      bindings:
        mq_consume:
          destination: orderTopic
          group: group1
          tag: orderTag1